# Generated by Django 4.2.9 on 2026-05-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Factory', 'Factory'), ('Products', 'Products'), ('Projects', 'Projects')], default='Factory', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary or external image URL')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Standard', 'Standard'), ('Decorative', 'Decorative'), ('Eco', 'Eco'), ('Boundary', 'Boundary')], default='Standard', max_length=50)),
                ('description', models.TextField()),
                ('sizes', models.JSONField(default=list, help_text='List of available sizes e.g. ["200×100×60mm"]')),
                ('thickness', models.JSONField(default=list, help_text='List of thickness options e.g. ["60mm", "80mm"]')),
                ('strength', models.CharField(help_text='Compressive strength e.g. 35 N/mm²', max_length=50)),
                ('applications', models.JSONField(default=list, help_text='List of applications')),
                ('colors', models.JSONField(default=list, help_text='Available colors')),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('features', models.JSONField(default=list, help_text='Key features list')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary or external image URL')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of service features')),
                ('applications', models.JSONField(default=list, help_text='List of applicable areas')),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Kartik Paver Industries', max_length=200)),
                ('tagline', models.CharField(default='Premium Quality Paver Block Solutions', max_length=300)),
                ('phone_primary', models.CharField(default='+91 90548 39964', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(default='kartikpaverindustries@gmail.com', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(default='Plot No C10, Near Atul Metal Latur, 1 No MIDC, Latur - 413531, Maharashtra')),
                ('whatsapp_number', models.CharField(default='919054839964', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps embed URL')),
                ('hero_banner_title', models.CharField(default='Premium Quality Paver Block Solutions', max_length=300)),
                ('hero_banner_subtitle', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Civil Contractor', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review', models.TextField()),
                ('project', models.CharField(blank=True, help_text='Project name/description', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
