# Generated by Django 5.2.14 on 2026-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_image_url_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default='In Stock', help_text='Stock status', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Primary color', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='e.g. Clay, Concrete', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(blank=True, help_text='e.g. 295 x 92 x 92 Mm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, help_text='e.g. Rectangle, Square', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, help_text='e.g. Hollow bricks, Solid blocks', max_length=100),
        ),
    ]
